import Foundation

enum AppLanguage: String, Codable, CaseIterable, Identifiable {
    case system
    case english
    case korean
    case japanese
    case chineseSimplified

    var id: String { rawValue }

    var pickerTitle: String {
        switch self {
        case .system: "System Default"
        case .english: "English"
        case .korean: "한국어"
        case .japanese: "日本語"
        case .chineseSimplified: "简体中文"
        }
    }

    var resolved: AppLanguage {
        guard self == .system else {
            return self
        }

        let localeIdentifier = Locale.preferredLanguages.first ?? Locale.current.identifier
        let normalized = localeIdentifier.lowercased()
        if normalized.hasPrefix("ko") {
            return .korean
        }
        if normalized.hasPrefix("ja") {
            return .japanese
        }
        if normalized.hasPrefix("zh") {
            return .chineseSimplified
        }
        return .english
    }
}

enum OverlayDisplayScope: String, Codable, CaseIterable, Identifiable {
    case gameWindow
    case activeGameDisplay
    case allDisplays

    var id: String { rawValue }

    var label: String {
        switch self {
        case .gameWindow: "Game Window"
        case .activeGameDisplay: "Active Game Display"
        case .allDisplays: "All Displays"
        }
    }
}

struct InterfaceSettings: Codable, Equatable {
    var language: AppLanguage
    var overlayDisplayScope: OverlayDisplayScope

    static let standard = InterfaceSettings(language: .system, overlayDisplayScope: .gameWindow)
    static let legacy = InterfaceSettings(language: .system, overlayDisplayScope: .activeGameDisplay)

    enum CodingKeys: String, CodingKey {
        case language
        case overlayDisplayScope
    }

    init(language: AppLanguage, overlayDisplayScope: OverlayDisplayScope) {
        self.language = language
        self.overlayDisplayScope = overlayDisplayScope
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        language = try container.decodeIfPresent(AppLanguage.self, forKey: .language) ?? .system
        overlayDisplayScope = try container.decodeIfPresent(OverlayDisplayScope.self, forKey: .overlayDisplayScope) ?? .activeGameDisplay
    }
}

struct AppLocalizer {
    let language: AppLanguage

    func string(_ key: String) -> String {
        guard language.resolved != .english else {
            return key
        }
        return Self.translations[language.resolved]?[key] ?? key
    }

    func languagePickerTitle(for language: AppLanguage) -> String {
        if language == .system {
            return string(language.pickerTitle)
        }
        return language.pickerTitle
    }

    func mode(_ mode: ComfortMode) -> String {
        string(mode.label)
    }

    func category(_ category: GameCategory) -> String {
        string(category.label)
    }

    func severity(_ severity: RecommendationSeverity) -> String {
        string(severity.label)
    }

    func recommendationStatus(_ status: RecommendationStatus) -> String {
        string(status.label)
    }

    func hotkeyAction(_ action: HotkeyAction) -> String {
        string(action.label)
    }

    func phrase(_ value: String) -> String {
        string(value)
    }

    func highRiskReason(_ reason: String) -> String {
        let prefix = "User discomfort score reached "
        if reason.hasPrefix(prefix) {
            let score = String(reason.dropFirst(prefix.count))
            return String(format: string("User discomfort score reached %@"), score)
        }
        return string(reason)
    }
}

extension AppState {
    var localizer: AppLocalizer {
        AppLocalizer(language: language)
    }

    func t(_ key: String) -> String {
        localizer.string(key)
    }

    var localizedCurrentGameName: String {
        activeProfile?.displayName ?? currentApp?.localizedName ?? localizer.string("None")
    }

    var localizedCaptureModeDescription: String {
        localizer.phrase(captureModeDescription)
    }

    var localizedCaptureReadinessDescription: String {
        localizer.phrase(captureReadinessDescription)
    }

    var localizedStatusMessage: String {
        localizer.phrase(statusMessage)
    }

    var localizedDiagnosticsStatusMessage: String {
        localizer.phrase(diagnosticsStatusMessage)
    }
}

extension AppLocalizer {
    static func translationTable(for language: AppLanguage) -> [String: String] {
        translations[language] ?? [:]
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .korean: korean,
        .japanese: japanese,
        .chineseSimplified: chineseSimplified
    ]

    private static let korean: [String: String] = [
        "System Default": "시스템 기본값",
        "Language": "언어",
        "Interface Language": "인터페이스 언어",
        "Interface": "인터페이스",
        "Language preference saved.": "언어 설정을 저장했습니다.",
        "Overlay Display": "오버레이 표시 화면",
        "Active Game Display": "게임이 실행 중인 화면",
        "All Displays": "모든 화면",
        "Overlay display preference saved.": "오버레이 표시 화면 설정을 저장했습니다.",
        "Open SeaLegs controls": "SeaLegs 제어 메뉴 열기",
        "%@ overlay is off.": "%@ 오버레이가 꺼졌습니다.",
        "%@ is already registered.": "%@은(는) 이미 등록되어 있습니다.",
        "manual overlay": "수동 오버레이",
        "Overlay hidden.": "오버레이를 숨겼습니다.",
        "Overlay visible.": "오버레이를 표시했습니다.",
        "Input signal preference saved.": "입력 신호 설정을 저장했습니다.",
        "Input signal monitoring disabled.": "입력 신호 모니터링을 껐습니다.",
        "Input Monitoring permission is needed. The input signal will start automatically after permission is granted and SeaLegs is reopened.": "입력 모니터링 권한이 필요합니다. 권한을 허용하고 SeaLegs를 다시 열면 입력 신호가 자동으로 시작됩니다.",
        "paused while Mac sleeps": "Mac 잠자기 중 일시 정지됨",
        "Hotkeys registered.": "단축키를 등록했습니다.",
        "Some hotkeys are unavailable. Use the menu bar actions as fallback.": "일부 단축키를 사용할 수 없습니다. 메뉴바 기능을 대신 사용하세요.",
        "Emergency overlay ended. Record discomfort when it is safe to do so.": "응급 오버레이가 끝났습니다. 안전할 때 불편감 점수를 기록하세요.",
        "Built-in template profiles cannot be deleted.": "기본 템플릿 프로필은 삭제할 수 없습니다.",
        "Start a registered game before recording a discomfort score.": "불편감 점수를 기록하기 전에 등록된 게임을 실행하세요.",
        "Failed to save settings: %@": "설정 저장 실패: %@",
        "Add a game profile before applying calibration.": "캘리브레이션을 적용하기 전에 게임 프로필을 추가하세요.",
        "Session logs may contain numeric motion metrics, profile identifiers, permission state, optional discomfort ratings, and emergency events.": "세션 로그에는 숫자 움직임 지표, 프로필 식별자, 권한 상태, 선택적 불편감 점수, 응급 이벤트가 포함될 수 있습니다.",
        "Template profile names and categories are fixed, but their visual settings can be adjusted.": "템플릿 프로필의 이름과 카테고리는 고정되지만 시각 설정은 조절할 수 있습니다.",
        "Bring the game to the front once, return to SeaLegs, then add it.": "게임을 한 번 앞에 표시한 뒤 SeaLegs로 돌아와 추가하세요.",
        "Failed to save language preference: %@": "언어 설정 저장 실패: %@",
        "General": "일반",
        "Profiles": "프로필",
        "Overlay": "오버레이",
        "Adaptive": "적응형",
        "Assistant": "도우미",
        "Calibration": "캘리브레이션",
        "Hotkeys": "단축키",
        "Privacy": "개인정보",
        "Reports": "리포트",
        "Debug": "디버그",
        "System": "시스템",
        "Status": "상태",
        "Current App": "현재 앱",
        "Current Game": "현재 게임",
        "Mode": "모드",
        "Capture": "캡처",
        "Message": "메시지",
        "Actions": "작업",
        "Add Current App": "현재 앱 추가",
        "Toggle Overlay": "오버레이 전환",
        "Show Feature Demo": "기능 데모 보기",
        "Feature demo overlay is visible.": "기능 데모 오버레이가 표시됩니다.",
        "Shows center dot, crosshair, horizon, dashboard, nose, and peripheral frame.": "중앙 점, 조준선, 수평선, 대시보드, 가상 코, 주변부 프레임을 보여줍니다.",
        "Feature demo temporarily shows every visible aid at high contrast, without changing the selected profile.": "기능 데모는 선택한 프로필을 바꾸지 않고 모든 시각 보조 요소를 고대비로 잠시 보여줍니다.",
        "Apply Recommended Visual Aids": "권장 시각 보조 요소 적용",
        "Recommended visual aids applied.": "권장 시각 보조 요소를 적용했습니다.",
        "Last calibration undone.": "마지막 캘리브레이션을 되돌렸습니다.",
        "Failed to save profiles: %@": "프로필 저장 실패: %@",
        "feature demo": "기능 데모",
        "Open Session Report": "세션 리포트 열기",
        "Toggle Emergency": "응급 모드 전환",
        "Support": "지원 범위",
        "Supported: macOS 14+ on Apple Silicon, windowed/borderless games recommended.": "지원: Apple Silicon의 macOS 14 이상, 창 모드/테두리 없는 창 게임 권장.",
        "Limited: native fullscreen games depending on macOS Spaces behavior.": "제한: macOS Spaces 동작에 따라 네이티브 전체화면 게임은 제한될 수 있음.",
        "Comfort": "편안함",
        "Off": "끔",
        "Low": "낮음",
        "Medium": "중간",
        "High": "높음",
        "Vignette": "비네트",
        "Base Opacity": "기본 불투명도",
        "Max Opacity": "최대 불투명도",
        "Motion Inner Radius": "움직임 내부 반경",
        "Visual Anchors": "시각 기준점",
        "Center Dot": "중앙 점",
        "Center Dot Opacity": "중앙 점 불투명도",
        "Minimal Crosshair": "미니멀 조준선",
        "Crosshair Opacity": "조준선 불투명도",
        "Horizon Guide": "수평선 가이드",
        "Horizon Position": "수평선 위치",
        "Dashboard Frame": "대시보드 프레임",
        "Virtual Nose": "가상 코",
        "Peripheral Frame": "주변부 프레임",
        "Peripheral Frame Opacity": "주변부 프레임 불투명도",
        "Current Overlay": "현재 오버레이",
        "Opacity": "불투명도",
        "Inner Radius": "내부 반경",
        "Emergency": "응급",
        "On": "켜짐",
        "Screen Recording": "화면 기록",
        "Access": "접근",
        "Granted": "허용됨",
        "Not Granted": "허용 안 됨",
        "Request Access": "접근 요청",
        "Open Privacy Settings": "개인정보 설정 열기",
        "Refresh": "새로고침",
        "Restart SeaLegs": "SeaLegs 재시작",
        "After allowing SeaLegs in System Settings, return here and press Refresh.": "시스템 설정에서 SeaLegs를 허용한 뒤 여기로 돌아와 새로고침을 누르세요.",
        "After allowing SeaLegs in System Settings, restart SeaLegs, then press Refresh.": "시스템 설정에서 SeaLegs를 허용한 뒤 SeaLegs를 재시작하고 새로고침을 누르세요.",
        "Metrics": "지표",
        "Motion Score": "움직임 점수",
        "Peripheral Motion": "주변부 움직임",
        "Rotation Proxy": "회전 추정치",
        "Radial Expansion": "방사형 확장",
        "Visual Cadence Risk": "시각 리듬 위험",
        "Adaptive Analysis": "적응형 분석",
        "Low Power Mode": "저전력 모드",
        "Analysis FPS: %d": "분석 FPS: %d",
        "Effective FPS": "실제 FPS",
        "Low Power Mode caps analysis at 12 FPS and reduces analysis resolution.": "저전력 모드는 분석을 12 FPS로 제한하고 분석 해상도를 낮춥니다.",
        "Discomfort Prompts": "불편감 확인",
        "Periodic discomfort prompts": "주기적으로 불편감 확인",
        "Prompt interval: %d min": "확인 간격: %d분",
        "Game Settings Assistant": "게임 설정 도우미",
        "These recommendations are manual. SeaLegs will not change game files automatically.": "이 권장사항은 수동 적용용입니다. SeaLegs는 게임 파일을 자동으로 바꾸지 않습니다.",
        "Profile": "프로필",
        "Editing Profile": "편집할 프로필",
        "Profile Type": "프로필 유형",
        "Registered profile": "등록된 프로필",
        "Checklist": "체크리스트",
        "No profile is available.": "사용 가능한 프로필이 없습니다.",
        "Reset Checklist for Profile Category": "프로필 카테고리 체크리스트 초기화",
        "Reset this checklist?": "이 체크리스트를 초기화할까요?",
        "Reset Checklist": "체크리스트 초기화",
        "Cancel": "취소",
        "Critical": "중요",
        "Recommended": "권장",
        "Optional": "선택",
        "Not Checked": "확인 안 함",
        "Applied": "적용됨",
        "Ignored": "무시됨",
        "Not Available": "게임에서 없음",
        "Almost never uncomfortable": "거의 불편하지 않음",
        "Sometimes uncomfortable": "가끔 불편함",
        "Often uncomfortable": "자주 불편함",
        "Very sensitive": "매우 민감함",
        "Subtle center dot": "은은한 중앙 점",
        "No anchor": "기준점 없음",
        "Calibration Wizard": "캘리브레이션 마법사",
        "Calibration works without Screen Recording permission and updates the selected profile after confirmation.": "캘리브레이션은 화면 기록 권한 없이도 작동하며, 확인 후 선택된 프로필을 업데이트합니다.",
        "Target Profile": "대상 프로필",
        "Game Type": "게임 유형",
        "Category": "카테고리",
        "Sensitivity": "민감도",
        "Visual Anchor": "시각 기준점",
        "Preference": "선호 기준점",
        "Review / Apply Calibration": "캘리브레이션 검토 / 적용",
        "Undo Last Calibration": "마지막 캘리브레이션 되돌리기",
        "Apply calibration to selected profile?": "선택한 프로필에 캘리브레이션을 적용할까요?",
        "Apply Calibration": "캘리브레이션 적용",
        "This will update overlay strength, category, and checklist for the selected profile.": "선택한 프로필의 오버레이 강도, 카테고리, 체크리스트가 업데이트됩니다.",
        "Defaults": "기본값",
        "Registration": "등록 상태",
        "Retry Hotkey Registration": "단축키 다시 등록",
        "Fallback": "대체 방법",
        "All core actions are also available from the SeaLegs menu bar item.": "모든 핵심 작업은 SeaLegs 메뉴바 항목에서도 사용할 수 있습니다.",
        "Registered": "등록됨",
        "Unavailable (%d)": "사용 불가 (%d)",
        "Local Analysis": "로컬 분석",
        "Adaptive mode uses Screen Recording to process low-resolution frames locally.": "적응형 모드는 화면 기록으로 낮은 해상도 프레임을 로컬에서 처리합니다.",
        "No screenshots, video, audio, OCR, typed text, or raw mouse paths are stored.": "스크린샷, 영상, 오디오, OCR, 입력 텍스트, 원본 마우스 경로는 저장하지 않습니다.",
        "Only numeric motion metrics and optional discomfort ratings are written to session logs.": "세션 로그에는 숫자 움직임 지표와 선택적 불편감 점수만 기록됩니다.",
        "Permissions": "권한",
        "Screen Recording Requested": "화면 기록 요청됨",
        "Input Monitoring": "입력 모니터링",
        "Input Signal": "입력 신호",
        "Input Monitoring Access": "입력 모니터링 접근 권한",
        "The input signal preference is saved. macOS permission is requested only when enabled.": "입력 신호 설정은 저장됩니다. 활성화할 때만 macOS 권한을 요청합니다.",
        "Yes": "예",
        "No": "아니요",
        "Enabled": "활성화됨",
        "Optional, off by default": "선택 사항, 기본 꺼짐",
        "Request Screen Recording": "화면 기록 요청",
        "Open Screen Recording Settings": "화면 기록 설정 열기",
        "Enable Input Signal": "입력 신호 활성화",
        "Open Input Monitoring Settings": "입력 모니터링 설정 열기",
        "Session Logs": "세션 로그",
        "Store numeric session logs": "숫자 세션 로그 저장",
        "Sample interval: %.1fs": "샘플 간격: %.1f초",
        "Retention: %d days": "보관 기간: %d일",
        "Delete Stored Session Logs...": "저장된 세션 로그 삭제...",
        "Delete all stored session logs?": "저장된 세션 로그를 모두 삭제할까요?",
        "Delete Logs": "로그 삭제",
        "Diagnostics": "진단",
        "Diagnostics export includes numeric state and salted hashes, not screenshots, videos, OCR, typed text, raw app identifiers, or full paths.": "진단 내보내기에는 숫자 상태와 솔트 해시만 포함되며, 스크린샷, 영상, OCR, 입력 텍스트, 원본 앱 식별자, 전체 경로는 포함되지 않습니다.",
        "Export Diagnostics...": "진단 내보내기...",
        "Refresh Report": "리포트 새로고침",
        "Template profile": "템플릿 프로필",
        "Template profiles are built-in starting points and cannot be deleted.": "템플릿 프로필은 기본 시작점이며 삭제할 수 없습니다.",
        "Registered profiles are linked to an app and can be deleted.": "등록된 프로필은 앱과 연결되며 삭제할 수 있습니다.",
        "Display Name": "표시 이름",
        "Match": "매칭",
        "Bundle ID": "번들 ID",
        "Executable": "실행 파일",
        "Preview / Use": "미리보기 / 사용",
        "Preview Profile": "프로필 미리보기",
        "Active Profile": "활성 프로필",
        "Delete": "삭제",
        "Select a profile.": "프로필을 선택하세요.",
        "Delete this profile?": "이 프로필을 삭제할까요?",
        "Delete Profile": "프로필 삭제",
        "Comfort overlay for macOS 3D games.": "macOS 3D 게임용 편안함 오버레이.",
        "Add Current App as Game": "현재 앱을 게임으로 추가",
        "Test Overlay": "오버레이 테스트",
        "Overlay tested": "오버레이 테스트 완료",
        "Ready to test": "테스트 준비됨",
        "Create a registered profile for the app you want to use.": "사용할 앱의 등록 프로필을 만듭니다.",
        "No app added": "추가된 앱 없음",
        "Enable Adaptive Mode": "적응형 모드 활성화",
        "Adaptive Mode (Optional)": "적응형 모드(선택 사항)",
        "Access requested": "권한 요청됨",
        "Optional step": "선택 단계",
        "Open Settings": "설정 열기",
        "Screen Recording is only needed for Adaptive mode. Basic overlay works without permissions.": "화면 기록은 적응형 모드에만 필요합니다. 기본 오버레이는 권한 없이도 작동합니다.",
        "Done": "완료",
        "Skip for Now": "나중에 하기",
        "Duration": "시간",
        "Average Motion": "평균 움직임",
        "Peak Motion": "최대 움직임",
        "Average Discomfort": "평균 불편감",
        "Emergency Count": "응급 횟수",
        "Recommendations": "권장사항",
        "High Risk Moments": "고위험 순간",
        "No session report yet.": "아직 세션 리포트가 없습니다.",
        "Game": "게임",
        "Readiness": "준비 상태",
        "Last Sample": "최근 샘플",
        "No samples yet": "아직 샘플 없음",
        "%.1fs ago": "%.1f초 전",
        "Current App: %@": "현재 앱: %@",
        "Current Game: %@": "현재 게임: %@",
        "Emergency Mode": "응급 모드",
        "Add Current App as Game...": "현재 앱을 게임으로 추가...",
        "Record Discomfort Score...": "불편감 점수 기록...",
        "Open Settings...": "설정 열기...",
        "Session Report...": "세션 리포트...",
        "Debug HUD": "디버그 HUD",
        "Welcome to SeaLegs": "SeaLegs에 오신 것을 환영합니다",
        "Session Report": "세션 리포트",
        "Export SeaLegs Diagnostics": "SeaLegs 진단 내보내기",
        "Quit": "종료",
        "Overlay Toggle": "오버레이 전환",
        "Comfort Up": "편안함 증가",
        "Comfort Down": "편안함 감소",
        "Discomfort Score": "불편감 점수",
        "%@ overlay preview is visible.": "%@ 오버레이 미리보기가 표시됩니다.",
        "Preview": "미리보기",
        "Emergency comfort": "응급 편안함",
        "Stability %.0f%% · %@": "안정성 %.0f%% · %@",
        "Record discomfort score": "불편감 점수 기록",
        "0 = none, 20 = clear motion sickness.": "0 = 없음, 20 = 뚜렷한 멀미.",
        "Record": "기록",
        "Desktop FPS": "데스크톱 FPS",
        "Competitive FPS": "경쟁 FPS",
        "Third-person Action": "3인칭 액션",
        "Racing": "레이싱",
        "Flight / Space": "비행 / 우주",
        "Walking Simulator": "워킹 시뮬레이터",
        "General 3D": "일반 3D",
        "Motion Blur": "모션 블러",
        "Camera Shake": "카메라 흔들림",
        "Head Bob / View Bob": "헤드 밥 / 뷰 밥",
        "Weapon Sway": "무기 흔들림",
        "Chromatic Aberration": "색수차",
        "Film Grain": "필름 그레인",
        "Depth of Field": "피사계 심도",
        "Sprint FOV Effect": "질주 FOV 효과",
        "Mouse Acceleration": "마우스 가속",
        "Auto Camera Recenter": "자동 카메라 재중앙",
        "Field of View": "시야각",
        "Cockpit or Dashboard View": "조종석 또는 대시보드 시점",
        "Horizon / Cockpit Reference": "수평선 / 조종석 기준",
        "Off or Low": "끔 또는 낮음",
        "Low or Off": "낮음 또는 끔",
        "Tune after calibration": "캘리브레이션 후 조정",
        "Prefer stable cockpit/dashboard view when available": "가능하면 안정적인 조종석/대시보드 시점 권장",
        "Reduces visual smear during camera movement and sprinting.": "카메라 이동과 질주 중 화면 번짐을 줄입니다.",
        "Keeps the whole image from shaking during impacts, sprinting, and scripted events.": "충격, 질주, 연출 이벤트 중 전체 화면 흔들림을 줄입니다.",
        "Reduces repeated vertical camera motion while walking or running.": "걷거나 달릴 때 반복되는 수직 카메라 움직임을 줄입니다.",
        "Keeps the center view steadier during movement.": "이동 중 중앙 시야를 더 안정적으로 유지합니다.",
        "Removes color fringing near the edge of the image.": "화면 가장자리의 색 번짐을 제거합니다.",
        "Removes unnecessary visual noise.": "불필요한 시각 노이즈를 제거합니다.",
        "Reduces sudden focus shifts and blur changes.": "갑작스러운 초점 이동과 흐림 변화를 줄입니다.",
        "Avoids abrupt field-of-view changes while sprinting.": "질주 중 갑작스러운 시야각 변화를 피합니다.",
        "Makes camera movement more predictable.": "카메라 움직임을 더 예측 가능하게 만듭니다.",
        "Reduces camera motion that was not directly initiated by the player.": "플레이어가 직접 시작하지 않은 카메라 움직임을 줄입니다.",
        "Very low and very high FOV values can both feel uncomfortable depending on the game.": "게임에 따라 너무 낮거나 높은 FOV 모두 불편할 수 있습니다.",
        "A fixed vehicle reference can make rapid lateral motion easier to tolerate.": "고정된 차량 기준점은 빠른 좌우 움직임을 더 견디기 쉽게 만듭니다.",
        "A fixed horizon or cockpit frame gives your eyes a stable reference.": "고정된 수평선이나 조종석 프레임은 눈에 안정적인 기준점을 제공합니다.",
        "Motion": "움직임",
        "Motion score stayed high": "움직임 점수가 높게 유지됨",
        "User discomfort score reached %@": "사용자 불편감 점수 %@ 도달",
        "In-game settings checklist": "게임 내 설정 체크리스트",
        "Turn down or disable Motion Blur, Camera Shake, Head Bob, Chromatic Aberration, Film Grain, and Sprint FOV Effect.": "Motion Blur, Camera Shake, Head Bob, Chromatic Aberration, Film Grain, Sprint FOV Effect를 낮추거나 끄는 것을 권장합니다.",
        "Reduce camera rotation": "시점 회전 완화",
        "Camera rotation was strong. Try lowering in-game mouse sensitivity or turn speed.": "시점 회전이 강했습니다. 게임 내 mouse sensitivity 또는 turn speed를 낮춰보세요.",
        "Reduce sprint and FOV effects": "질주/FOV 효과 완화",
        "Fast forward-motion sections were frequent. Try lowering sprint FOV effect, motion blur, and camera shake.": "빠른 전진 구간이 많았습니다. sprint FOV effect, motion blur, camera shake를 낮춰보세요.",
        "Reduce vertical bobbing": "상하 흔들림 완화",
        "Vertical motion was strong. Turning off head bob or view bob is recommended.": "상하 흔들림이 강했습니다. head bob/view bob 옵션을 끄는 것이 좋습니다.",
        "Improve frame stability": "화면 안정성 개선",
        "Visual stability was low. Try lowering graphics settings or setting a stable FPS cap.": "화면 안정성이 낮았습니다. 그래픽 옵션을 낮추거나 안정적인 FPS cap을 설정해보세요.",
        "Increase profile strength": "프로필 강도 상향",
        "Emergency mode or high discomfort was recorded. Consider raising the current profile's vignette max strength by one step.": "Emergency 또는 높은 불편감 기록이 있었습니다. 현재 profile의 vignette max strength를 한 단계 올리는 것을 권장합니다.",
        "Keep current settings": "현재 설정 유지",
        "High-risk signals were limited. Keeping the current comfort profile is reasonable.": "높은 위험 신호가 적었습니다. 현재 comfort profile을 유지해도 좋습니다.",
        "Ready": "준비됨",
        "Basic overlay available": "기본 오버레이 사용 가능",
        "No diagnostics export yet.": "아직 진단 내보내기가 없습니다.",
        "None": "없음",
        "stopped": "정지됨",
        "preview": "미리보기",
        "fallback: basic overlay": "대체: 기본 오버레이",
        "Screen Recording required": "화면 기록 필요",
        "Waiting for samples": "샘플 대기 중",
        "Some hotkeys could not be registered. Use the menu bar actions as fallback.": "일부 단축키를 등록하지 못했습니다. 메뉴바 작업을 대체 방법으로 사용하세요.",
        "Screen Recording permission granted.": "화면 기록 권한이 허용되었습니다.",
        "Allow Screen Recording in System Settings, then return to SeaLegs and press Refresh.": "시스템 설정에서 화면 기록을 허용한 뒤 SeaLegs로 돌아와 새로고침을 누르세요.",
        "Allow Screen Recording in System Settings, restart SeaLegs, then press Refresh.": "시스템 설정에서 화면 기록을 허용한 뒤 SeaLegs를 재시작하고 새로고침을 누르세요.",
        "Open Privacy & Security > Screen Recording manually, allow SeaLegs, restart the app, then press Refresh.": "개인정보 보호 및 보안 > 화면 기록을 직접 열어 SeaLegs를 허용하고 앱을 재시작한 뒤 새로고침을 누르세요.",
        "If SeaLegs is enabled in Screen Recording, restart the app and press Refresh.": "화면 기록에서 SeaLegs가 켜져 있다면 앱을 재시작한 뒤 새로고침을 누르세요.",
        "Use Request Access to open Screen Recording settings, allow SeaLegs, restart the app, then press Refresh.": "접근 요청을 눌러 화면 기록 설정을 열고 SeaLegs를 허용한 뒤 앱을 재시작하고 새로고침을 누르세요.",
        "Failed to restart SeaLegs: %@": "SeaLegs 재시작 실패: %@",
        "Input signal monitoring enabled.": "입력 신호 모니터링이 활성화되었습니다.",
        "Input Monitoring permission is needed for mouse turn prediction.": "마우스 회전 예측에는 입력 모니터링 권한이 필요합니다.",
        "Allow Input Monitoring in System Settings, restart SeaLegs, then press Refresh.": "시스템 설정에서 입력 모니터링을 허용한 뒤 SeaLegs를 재시작하고 새로고침을 누르세요.",
        "Open Privacy & Security > Input Monitoring manually, allow SeaLegs, restart the app, then press Refresh.": "개인정보 보호 및 보안 > 입력 모니터링을 직접 열어 SeaLegs를 허용하고 앱을 재시작한 뒤 새로고침을 누르세요.",
        "Diagnostics exported.": "진단을 내보냈습니다.",
        "Exported to %@.": "%@에 내보냈습니다.",
        "Export failed: %@": "내보내기 실패: %@",
        "Privacy settings saved.": "개인정보 설정을 저장했습니다.",
        "Stored session logs deleted.": "저장된 세션 로그를 삭제했습니다.",
        "Adaptive capture fallback: %@": "적응형 캡처 대체: %@",
        "Adaptive paused": "적응형 일시 중지",
        "Select a registered game to enable adaptive capture.": "적응형 캡처를 활성화하려면 등록된 게임을 선택하세요.",
        "Adaptive requires an active registered game.": "적응형 모드에는 활성화된 등록 게임이 필요합니다.",
        "Screen Recording permission needed": "화면 기록 권한 필요",
        "Adaptive waiting": "적응형 대기 중",
        "Temporary stronger overlay": "일시적으로 더 강한 오버레이",
        "Game Window": "게임 창",
        "Game Window (Waiting for Game)": "게임 창(게임 대기 중)",
        "Active Game Display (Window Fallback)": "게임 화면(창 감지 대체)",
        "Compatibility": "호환성",
        "Startup": "시작",
        "Resolved Overlay Target": "현재 오버레이 대상",
        "The game window was not available, so SeaLegs is using the active game display.": "게임 창을 찾지 못해 현재 게임 화면을 사용하고 있습니다.",
        "Launch SeaLegs at Login": "로그인 시 SeaLegs 실행",
        "Launch at Login Status": "로그인 시 실행 상태",
        "Not Registered": "등록되지 않음",
        "Requires Approval": "승인 필요",
        "Unavailable": "사용할 수 없음",
        "Approve SeaLegs in System Settings > General > Login Items.": "시스템 설정 > 일반 > 로그인 항목에서 SeaLegs를 승인하세요.",
        "Open Login Items Settings": "로그인 항목 설정 열기",
        "Center Dot Horizontal Position": "중앙 점 가로 위치",
        "Center Dot Vertical Position": "중앙 점 세로 위치",
        "Crosshair Horizontal Position": "조준선 가로 위치",
        "Crosshair Vertical Position": "조준선 세로 위치",
        "Reset Anchor Positions": "기준점 위치 초기화",
        "Compatibility Check": "호환성 확인",
        "Run this check with the game visible to confirm targeting and Adaptive readiness.": "게임을 화면에 표시한 상태에서 대상 지정과 적응형 준비 상태를 확인하세요.",
        "Registered Game": "등록된 게임",
        "Not Active": "실행 중 아님",
        "Active": "실행 중",
        "Overlay Target": "오버레이 대상",
        "Adaptive Samples": "적응형 샘플",
        "Launch at Login": "로그인 시 실행",
        "Run Overlay Test": "오버레이 테스트 실행",
        "Copy Compatibility Report": "호환성 리포트 복사",
        "The compatibility report contains operational status only and excludes screenshots, frames, paths, window titles, and raw application identifiers.": "호환성 리포트에는 동작 상태만 포함되며 스크린샷, 프레임, 경로, 창 제목, 원본 앱 식별자는 제외됩니다.",
        "Compatibility check not run yet.": "아직 호환성 확인을 실행하지 않았습니다.",
        "Overlay test started. Confirm that the visual guides fit the game area.": "오버레이 테스트를 시작했습니다. 시각 기준점이 게임 영역에 맞는지 확인하세요.",
        "Compatibility report copied.": "호환성 리포트를 복사했습니다.",
        "Export Selected Profile...": "선택한 프로필 내보내기...",
        "Import Profiles...": "프로필 가져오기...",
        "Export Custom Profiles...": "사용자 프로필 내보내기...",
        "Profile Import Preview": "프로필 가져오기 미리보기",
        "%d profile(s) ready to import.": "%d개 프로필을 가져올 준비가 되었습니다.",
        "Conflicts": "충돌",
        "Warnings": "경고",
        "Replace Existing": "기존 항목 교체",
        "Import Profiles": "프로필 가져오기",
        "Keep Both": "둘 다 유지",
        "Export SeaLegs Profiles": "SeaLegs 프로필 내보내기",
        "Import SeaLegs Profiles": "SeaLegs 프로필 가져오기",
        "Select a profile before exporting.": "내보낼 프로필을 먼저 선택하세요.",
        "No custom profiles are available to export.": "내보낼 사용자 프로필이 없습니다.",
        "Review the imported profiles before applying changes.": "변경 사항을 적용하기 전에 가져올 프로필을 검토하세요.",
        "Profile import failed: %@": "프로필 가져오기 실패: %@",
        "Profile import cancelled.": "프로필 가져오기를 취소했습니다.",
        "Imported %d profile(s).": "%d개 프로필을 가져왔습니다.",
        "Launch at Login requires approval in System Settings.": "로그인 시 실행은 시스템 설정에서 승인이 필요합니다.",
        "Launch at Login updated.": "로그인 시 실행 설정을 업데이트했습니다.",
        "Failed to update Launch at Login: %@": "로그인 시 실행 업데이트 실패: %@",
        "Exported %d profile(s) to %@.": "%d개 프로필을 %@에 내보냈습니다.",
        "Profile export failed: %@": "프로필 내보내기 실패: %@",
        "This profile has no app match and must be reconnected before automatic matching can work.": "이 프로필에는 연결된 앱이 없습니다. 자동 매칭을 사용하려면 게임에 다시 연결해야 합니다.",
        "Built-in templates are protected and will be kept as separate profiles.": "기본 템플릿은 보호되며 별도의 프로필로 유지됩니다.",
        "Keep Both imports conflicting profiles without an app match to avoid ambiguous automatic activation.": "자동 활성화 충돌을 막기 위해 '둘 다 유지'로 가져온 충돌 프로필은 앱 연결을 해제합니다.",
        "A linked imported profile can activate automatically when its matching app becomes active.": "연결된 가져오기 프로필은 일치하는 앱이 활성화되면 자동으로 실행될 수 있습니다.",
        "Unlinked": "연결되지 않음",
        "Custom profile": "사용자 프로필",
        "Unlinked custom profiles can be previewed or linked to the current app.": "연결되지 않은 사용자 프로필은 미리 보거나 현재 앱에 연결할 수 있습니다.",
        "Link to Current App": "현재 앱에 연결",
        "Select a custom profile before linking an app.": "앱을 연결할 사용자 프로필을 먼저 선택하세요.",
        "No application is available to link.": "연결할 수 있는 앱이 없습니다.",
        "This app is already linked to %@.": "이 앱은 이미 %@ 프로필에 연결되어 있습니다.",
        "Linked %@ to the selected profile.": "%@ 앱을 선택한 프로필에 연결했습니다.",
        "App": "앱"
    ]

    private static let japanese: [String: String] = [
        "System Default": "システム既定",
        "Language": "言語",
        "Interface Language": "インターフェース言語",
        "Language preference saved.": "言語設定を保存しました。",
        "Failed to save language preference: %@": "言語設定の保存に失敗しました: %@",
        "General": "一般",
        "Profiles": "プロファイル",
        "Overlay": "オーバーレイ",
        "Adaptive": "適応",
        "Assistant": "アシスタント",
        "Calibration": "キャリブレーション",
        "Hotkeys": "ホットキー",
        "Privacy": "プライバシー",
        "Reports": "レポート",
        "Debug": "デバッグ",
        "Status": "状態",
        "Current App": "現在のアプリ",
        "Current Game": "現在のゲーム",
        "Mode": "モード",
        "Capture": "キャプチャ",
        "Message": "メッセージ",
        "Actions": "操作",
        "Add Current App": "現在のアプリを追加",
        "Toggle Overlay": "オーバーレイ切替",
        "Open Session Report": "セッションレポートを開く",
        "Toggle Emergency": "緊急モード切替",
        "Support": "対応範囲",
        "Supported: macOS 14+ on Apple Silicon, windowed/borderless games recommended.": "対応: Apple Silicon の macOS 14 以降。ウィンドウまたはボーダーレス表示のゲームを推奨します。",
        "Limited: native fullscreen games depending on macOS Spaces behavior.": "制限: macOS Spaces の動作により、ネイティブ全画面ゲームでは制限される場合があります。",
        "Comfort": "快適性",
        "Off": "オフ",
        "Low": "低",
        "Medium": "中",
        "High": "高",
        "Vignette": "ビネット",
        "Base Opacity": "基本不透明度",
        "Max Opacity": "最大不透明度",
        "Motion Inner Radius": "動作時の内側半径",
        "Visual Anchors": "視覚アンカー",
        "Center Dot": "中央ドット",
        "Center Dot Opacity": "中央ドット不透明度",
        "Minimal Crosshair": "最小クロスヘア",
        "Crosshair Opacity": "クロスヘア不透明度",
        "Horizon Guide": "水平線ガイド",
        "Horizon Position": "水平線位置",
        "Dashboard Frame": "ダッシュボード枠",
        "Virtual Nose": "仮想ノーズ",
        "Peripheral Frame": "周辺フレーム",
        "Peripheral Frame Opacity": "周辺フレーム不透明度",
        "Current Overlay": "現在のオーバーレイ",
        "Opacity": "不透明度",
        "Inner Radius": "内側半径",
        "Emergency": "緊急",
        "On": "オン",
        "Screen Recording": "画面収録",
        "Access": "アクセス",
        "Granted": "許可済み",
        "Not Granted": "未許可",
        "Request Access": "アクセスを要求",
        "Open Privacy Settings": "プライバシー設定を開く",
        "Refresh": "更新",
        "Restart SeaLegs": "SeaLegs を再起動",
        "After allowing SeaLegs in System Settings, return here and press Refresh.": "システム設定で SeaLegs を許可した後、ここに戻って更新してください。",
        "After allowing SeaLegs in System Settings, restart SeaLegs, then press Refresh.": "システム設定で SeaLegs を許可した後、SeaLegs を再起動してから更新してください。",
        "Metrics": "指標",
        "Motion Score": "動きスコア",
        "Peripheral Motion": "周辺の動き",
        "Rotation Proxy": "回転推定",
        "Radial Expansion": "放射状拡大",
        "Visual Cadence Risk": "視覚リズムリスク",
        "Game Settings Assistant": "ゲーム設定アシスタント",
        "These recommendations are manual. SeaLegs will not change game files automatically.": "これらの推奨は手動用です。SeaLegs がゲームファイルを自動変更することはありません。",
        "Profile": "プロファイル",
        "Checklist": "チェックリスト",
        "No profile is available.": "利用できるプロファイルがありません。",
        "Reset Checklist for Profile Category": "プロファイル分類のチェックリストをリセット",
        "Reset this checklist?": "このチェックリストをリセットしますか？",
        "Reset Checklist": "チェックリストをリセット",
        "Cancel": "キャンセル",
        "Critical": "重要",
        "Recommended": "推奨",
        "Optional": "任意",
        "Not Checked": "未確認",
        "Applied": "適用済み",
        "Ignored": "無視",
        "Not Available": "ゲーム内に無し",
        "Almost never uncomfortable": "ほとんど不快にならない",
        "Sometimes uncomfortable": "時々不快",
        "Often uncomfortable": "よく不快",
        "Very sensitive": "とても敏感",
        "Subtle center dot": "控えめな中央ドット",
        "No anchor": "アンカーなし",
        "Calibration Wizard": "キャリブレーションウィザード",
        "Calibration works without Screen Recording permission and updates the selected profile after confirmation.": "キャリブレーションは画面収録権限なしで動作し、確認後に選択中のプロファイルを更新します。",
        "Target Profile": "対象プロファイル",
        "Game Type": "ゲーム種別",
        "Category": "カテゴリ",
        "Sensitivity": "感度",
        "Visual Anchor": "視覚アンカー",
        "Preference": "設定",
        "Review / Apply Calibration": "確認 / キャリブレーション適用",
        "Undo Last Calibration": "前回のキャリブレーションを戻す",
        "Apply calibration to selected profile?": "選択中のプロファイルにキャリブレーションを適用しますか？",
        "Apply Calibration": "キャリブレーションを適用",
        "This will update overlay strength, category, and checklist for the selected profile.": "選択中のプロファイルのオーバーレイ強度、カテゴリ、チェックリストを更新します。",
        "Defaults": "既定",
        "Fallback": "代替",
        "All core actions are also available from the SeaLegs menu bar item.": "主要操作は SeaLegs のメニューバー項目からも利用できます。",
        "Registered": "登録済み",
        "Unavailable (%d)": "利用不可 (%d)",
        "Local Analysis": "ローカル解析",
        "Adaptive mode uses Screen Recording to process low-resolution frames locally.": "適応モードでは画面収録を使い、低解像度フレームをローカルで処理します。",
        "No screenshots, video, audio, OCR, typed text, or raw mouse paths are stored.": "スクリーンショット、動画、音声、OCR、入力文字、元のマウス経路は保存しません。",
        "Only numeric motion metrics and optional discomfort ratings are written to session logs.": "セッションログには数値の動き指標と任意の不快度評価のみを書き込みます。",
        "Permissions": "権限",
        "Screen Recording Requested": "画面収録要求済み",
        "Input Monitoring": "入力監視",
        "Yes": "はい",
        "No": "いいえ",
        "Enabled": "有効",
        "Optional, off by default": "任意、既定ではオフ",
        "Request Screen Recording": "画面収録を要求",
        "Open Screen Recording Settings": "画面収録設定を開く",
        "Enable Input Signal": "入力信号を有効化",
        "Open Input Monitoring Settings": "入力監視設定を開く",
        "Session Logs": "セッションログ",
        "Store numeric session logs": "数値セッションログを保存",
        "Sample interval: %.1fs": "サンプル間隔: %.1f秒",
        "Retention: %d days": "保持期間: %d日",
        "Delete Stored Session Logs...": "保存済みセッションログを削除...",
        "Delete all stored session logs?": "保存済みセッションログをすべて削除しますか？",
        "Delete Logs": "ログを削除",
        "Diagnostics": "診断",
        "Diagnostics export includes numeric state and salted hashes, not screenshots, videos, OCR, typed text, raw app identifiers, or full paths.": "診断エクスポートには数値状態とソルト付きハッシュのみが含まれ、スクリーンショット、動画、OCR、入力文字、元のアプリ識別子、完全なパスは含まれません。",
        "Export Diagnostics...": "診断をエクスポート...",
        "Refresh Report": "レポートを更新",
        "Template profile": "テンプレートプロファイル",
        "Display Name": "表示名",
        "Match": "一致条件",
        "Bundle ID": "バンドル ID",
        "Executable": "実行ファイル",
        "Preview / Use": "プレビュー / 使用",
        "Delete": "削除",
        "Select a profile.": "プロファイルを選択してください。",
        "Delete this profile?": "このプロファイルを削除しますか？",
        "Delete Profile": "プロファイルを削除",
        "Comfort overlay for macOS 3D games.": "macOS 3D ゲーム向けの快適化オーバーレイ。",
        "Add Current App as Game": "現在のアプリをゲームとして追加",
        "Test Overlay": "オーバーレイをテスト",
        "Enable Adaptive Mode": "適応モードを有効化",
        "Open Settings": "設定を開く",
        "Screen Recording is only needed for Adaptive mode. Basic overlay works without permissions.": "画面収録が必要なのは適応モードのみです。基本オーバーレイは権限なしで動作します。",
        "Done": "完了",
        "Duration": "時間",
        "Average Motion": "平均の動き",
        "Peak Motion": "最大の動き",
        "Average Discomfort": "平均不快度",
        "Emergency Count": "緊急回数",
        "Recommendations": "推奨事項",
        "High Risk Moments": "高リスクの瞬間",
        "No session report yet.": "まだセッションレポートはありません。",
        "Game": "ゲーム",
        "Readiness": "準備状態",
        "Last Sample": "最新サンプル",
        "No samples yet": "まだサンプルなし",
        "%.1fs ago": "%.1f秒前",
        "Current App: %@": "現在のアプリ: %@",
        "Current Game: %@": "現在のゲーム: %@",
        "Emergency Mode": "緊急モード",
        "Add Current App as Game...": "現在のアプリをゲームとして追加...",
        "Record Discomfort Score...": "不快度スコアを記録...",
        "Open Settings...": "設定を開く...",
        "Session Report...": "セッションレポート...",
        "Debug HUD": "デバッグ HUD",
        "Welcome to SeaLegs": "SeaLegs へようこそ",
        "Session Report": "セッションレポート",
        "Export SeaLegs Diagnostics": "SeaLegs 診断をエクスポート",
        "Quit": "終了",
        "Overlay Toggle": "オーバーレイ切替",
        "Comfort Up": "快適性アップ",
        "Comfort Down": "快適性ダウン",
        "Discomfort Score": "不快度スコア",
        "%@ overlay preview is visible.": "%@ オーバーレイのプレビューを表示しています。",
        "Preview": "プレビュー",
        "Emergency comfort": "緊急快適化",
        "Stability %.0f%% · %@": "安定性 %.0f%% · %@",
        "Record discomfort score": "不快度スコアを記録",
        "0 = none, 20 = clear motion sickness.": "0 = なし、20 = 明確な乗り物酔い。",
        "Record": "記録",
        "Desktop FPS": "デスクトップ FPS",
        "Competitive FPS": "競技 FPS",
        "Third-person Action": "三人称アクション",
        "Racing": "レース",
        "Flight / Space": "フライト / 宇宙",
        "Walking Simulator": "ウォーキングシミュレーター",
        "General 3D": "一般 3D",
        "Motion Blur": "モーションブラー",
        "Camera Shake": "カメラ揺れ",
        "Head Bob / View Bob": "ヘッドボブ / ビューボブ",
        "Weapon Sway": "武器揺れ",
        "Chromatic Aberration": "色収差",
        "Film Grain": "フィルムグレイン",
        "Depth of Field": "被写界深度",
        "Sprint FOV Effect": "スプリント時 FOV 効果",
        "Mouse Acceleration": "マウス加速",
        "Auto Camera Recenter": "自動カメラ再センター",
        "Field of View": "視野角",
        "Cockpit or Dashboard View": "コックピットまたはダッシュボード視点",
        "Horizon / Cockpit Reference": "水平線 / コックピット基準",
        "Off or Low": "オフまたは低",
        "Low or Off": "低またはオフ",
        "Tune after calibration": "キャリブレーション後に調整",
        "Prefer stable cockpit/dashboard view when available": "可能なら安定したコックピット/ダッシュボード視点を優先",
        "Reduces visual smear during camera movement and sprinting.": "カメラ移動やスプリント中の視覚的なにじみを減らします。",
        "Keeps the whole image from shaking during impacts, sprinting, and scripted events.": "衝撃、スプリント、演出中に画面全体が揺れるのを抑えます。",
        "Reduces repeated vertical camera motion while walking or running.": "歩行や走行中の反復する上下カメラ動作を減らします。",
        "Keeps the center view steadier during movement.": "移動中の中央視界をより安定させます。",
        "Removes color fringing near the edge of the image.": "画面端付近の色にじみを取り除きます。",
        "Removes unnecessary visual noise.": "不要な視覚ノイズを取り除きます。",
        "Reduces sudden focus shifts and blur changes.": "急な焦点移動やぼけ変化を減らします。",
        "Avoids abrupt field-of-view changes while sprinting.": "スプリント中の急な視野角変化を避けます。",
        "Makes camera movement more predictable.": "カメラの動きを予測しやすくします。",
        "Reduces camera motion that was not directly initiated by the player.": "プレイヤーが直接始めていないカメラ動作を減らします。",
        "Very low and very high FOV values can both feel uncomfortable depending on the game.": "ゲームによっては、低すぎる FOV も高すぎる FOV も不快に感じる場合があります。",
        "A fixed vehicle reference can make rapid lateral motion easier to tolerate.": "固定された車両基準があると、急な横方向の動きを許容しやすくなります。",
        "A fixed horizon or cockpit frame gives your eyes a stable reference.": "固定された水平線やコックピット枠は、目に安定した基準を与えます。",
        "Motion": "動き",
        "Motion score stayed high": "動きスコアが高いままでした",
        "User discomfort score reached %@": "ユーザー不快度スコアが %@ に到達",
        "In-game settings checklist": "ゲーム内設定チェックリスト",
        "Turn down or disable Motion Blur, Camera Shake, Head Bob, Chromatic Aberration, Film Grain, and Sprint FOV Effect.": "Motion Blur、Camera Shake、Head Bob、Chromatic Aberration、Film Grain、Sprint FOV Effect を下げるか無効にすることを推奨します。",
        "Reduce camera rotation": "カメラ回転を抑える",
        "Camera rotation was strong. Try lowering in-game mouse sensitivity or turn speed.": "カメラ回転が強めでした。ゲーム内のマウス感度または回転速度を下げてみてください。",
        "Reduce sprint and FOV effects": "スプリント/FOV 効果を抑える",
        "Fast forward-motion sections were frequent. Try lowering sprint FOV effect, motion blur, and camera shake.": "高速な前進動作が多くありました。スプリント FOV 効果、モーションブラー、カメラ揺れを下げてみてください。",
        "Reduce vertical bobbing": "上下揺れを抑える",
        "Vertical motion was strong. Turning off head bob or view bob is recommended.": "上下の動きが強めでした。head bob または view bob をオフにすることを推奨します。",
        "Improve frame stability": "フレーム安定性を改善",
        "Visual stability was low. Try lowering graphics settings or setting a stable FPS cap.": "視覚的な安定性が低めでした。グラフィック設定を下げるか、安定した FPS 上限を設定してみてください。",
        "Increase profile strength": "プロファイル強度を上げる",
        "Emergency mode or high discomfort was recorded. Consider raising the current profile's vignette max strength by one step.": "緊急モードまたは高い不快度が記録されました。現在のプロファイルのビネット最大強度を 1 段階上げることを検討してください。",
        "Keep current settings": "現在の設定を維持",
        "High-risk signals were limited. Keeping the current comfort profile is reasonable.": "高リスク信号は少なめでした。現在の快適化プロファイルを維持して問題ありません。",
        "Ready": "準備完了",
        "Basic overlay available": "基本オーバーレイ利用可能",
        "No diagnostics export yet.": "診断エクスポートはまだありません。",
        "None": "なし",
        "stopped": "停止中",
        "preview": "プレビュー",
        "fallback: basic overlay": "代替: 基本オーバーレイ",
        "Screen Recording required": "画面収録が必要",
        "Waiting for samples": "サンプル待ち",
        "Some hotkeys could not be registered. Use the menu bar actions as fallback.": "一部のホットキーを登録できませんでした。代替としてメニューバー操作を使用してください。",
        "Screen Recording permission granted.": "画面収録権限が許可されました。",
        "Allow Screen Recording in System Settings, then return to SeaLegs and press Refresh.": "システム設定で画面収録を許可し、SeaLegs に戻って更新してください。",
        "Allow Screen Recording in System Settings, restart SeaLegs, then press Refresh.": "システム設定で画面収録を許可し、SeaLegs を再起動してから更新してください。",
        "Open Privacy & Security > Screen Recording manually, allow SeaLegs, restart the app, then press Refresh.": "プライバシーとセキュリティ > 画面収録を手動で開き、SeaLegs を許可してアプリを再起動してから更新してください。",
        "If SeaLegs is enabled in Screen Recording, restart the app and press Refresh.": "画面収録で SeaLegs が有効になっている場合は、アプリを再起動して更新してください。",
        "Use Request Access to open Screen Recording settings, allow SeaLegs, restart the app, then press Refresh.": "アクセス要求で画面収録設定を開き、SeaLegs を許可してアプリを再起動してから更新してください。",
        "Failed to restart SeaLegs: %@": "SeaLegs の再起動に失敗しました: %@",
        "Input signal monitoring enabled.": "入力信号の監視を有効にしました。",
        "Input Monitoring permission is needed for mouse turn prediction.": "マウス回転予測には入力監視権限が必要です。",
        "Allow Input Monitoring in System Settings, restart SeaLegs, then press Refresh.": "システム設定で入力監視を許可し、SeaLegs を再起動してから更新してください。",
        "Open Privacy & Security > Input Monitoring manually, allow SeaLegs, restart the app, then press Refresh.": "プライバシーとセキュリティ > 入力監視を手動で開き、SeaLegs を許可してアプリを再起動してから更新してください。",
        "Diagnostics exported.": "診断をエクスポートしました。",
        "Exported to %@.": "%@ にエクスポートしました。",
        "Export failed: %@": "エクスポート失敗: %@",
        "Privacy settings saved.": "プライバシー設定を保存しました。",
        "Stored session logs deleted.": "保存済みセッションログを削除しました。",
        "Adaptive capture fallback: %@": "適応キャプチャ代替: %@",
        "Adaptive paused": "適応を一時停止",
        "Select a registered game to enable adaptive capture.": "適応キャプチャを有効にするには登録済みゲームを選択してください。",
        "Adaptive requires an active registered game.": "適応モードにはアクティブな登録済みゲームが必要です。",
        "Screen Recording permission needed": "画面収録権限が必要",
        "Adaptive waiting": "適応待機中",
        "Temporary stronger overlay": "一時的に強いオーバーレイ",
        "Interface": "インターフェース",
        "Overlay Display": "オーバーレイの表示先",
        "Active Game Display": "ゲーム実行中のディスプレイ",
        "All Displays": "すべてのディスプレイ",
        "Overlay display preference saved.": "オーバーレイの表示先の設定を保存しました。",
        "Open SeaLegs controls": "SeaLegs のコントロールを開く",
        "%@ overlay is off.": "%@ のオーバーレイはオフです。",
        "%@ is already registered.": "%@ はすでに登録されています。",
        "manual overlay": "手動オーバーレイ",
        "Overlay hidden.": "オーバーレイを非表示にしました。",
        "Overlay visible.": "オーバーレイを表示しました。",
        "Input signal preference saved.": "入力信号の設定を保存しました。",
        "Input signal monitoring disabled.": "入力信号の監視を無効にしました。",
        "Input Monitoring permission is needed. The input signal will start automatically after permission is granted and SeaLegs is reopened.": "入力監視権限が必要です。許可後に SeaLegs を再度開くと、入力信号が自動的に開始されます。",
        "paused while Mac sleeps": "Mac のスリープ中は一時停止",
        "Hotkeys registered.": "ホットキーを登録しました。",
        "Some hotkeys are unavailable. Use the menu bar actions as fallback.": "一部のホットキーは利用できません。代替としてメニューバー操作を使用してください。",
        "Emergency overlay ended. Record discomfort when it is safe to do so.": "緊急オーバーレイが終了しました。安全なときに不快度を記録してください。",
        "Built-in template profiles cannot be deleted.": "組み込みのテンプレートプロファイルは削除できません。",
        "Start a registered game before recording a discomfort score.": "不快度スコアを記録する前に、登録済みゲームを開始してください。",
        "Failed to save settings: %@": "設定の保存に失敗しました: %@",
        "Add a game profile before applying calibration.": "キャリブレーションを適用する前にゲームプロファイルを追加してください。",
        "Session logs may contain numeric motion metrics, profile identifiers, permission state, optional discomfort ratings, and emergency events.": "セッションログには、数値の動き指標、プロファイル識別子、権限の状態、任意の不快度評価、緊急イベントが含まれる場合があります。",
        "Template profile names and categories are fixed, but their visual settings can be adjusted.": "テンプレートプロファイルの名前とカテゴリは固定ですが、視覚設定は調整できます。",
        "Bring the game to the front once, return to SeaLegs, then add it.": "ゲームを一度前面に出してから SeaLegs に戻り、追加してください。",
        "System": "システム",
        "Show Feature Demo": "機能デモを表示",
        "Feature demo overlay is visible.": "機能デモのオーバーレイが表示されています。",
        "Shows center dot, crosshair, horizon, dashboard, nose, and peripheral frame.": "中央ドット、クロスヘア、水平線、ダッシュボード枠、仮想ノーズ、周辺フレームを表示します。",
        "Feature demo temporarily shows every visible aid at high contrast, without changing the selected profile.": "機能デモでは、選択中のプロファイルを変更せずに、表示可能なすべての補助要素を高コントラストで一時的に表示します。",
        "Apply Recommended Visual Aids": "推奨の視覚補助を適用",
        "Recommended visual aids applied.": "推奨の視覚補助を適用しました。",
        "Last calibration undone.": "前回のキャリブレーションを元に戻しました。",
        "Failed to save profiles: %@": "プロファイルの保存に失敗しました: %@",
        "feature demo": "機能デモ",
        "Adaptive Analysis": "適応解析",
        "Low Power Mode": "低電力モード",
        "Analysis FPS: %d": "解析 FPS: %d",
        "Effective FPS": "実効 FPS",
        "Low Power Mode caps analysis at 12 FPS and reduces analysis resolution.": "低電力モードでは解析を 12 FPS に制限し、解析解像度を下げます。",
        "Discomfort Prompts": "不快度の確認",
        "Periodic discomfort prompts": "定期的に不快度を確認",
        "Prompt interval: %d min": "確認間隔: %d分",
        "Editing Profile": "編集するプロファイル",
        "Profile Type": "プロファイルの種類",
        "Registered profile": "登録済みプロファイル",
        "Registration": "登録",
        "Retry Hotkey Registration": "ホットキーの登録を再試行",
        "Input Signal": "入力信号",
        "Input Monitoring Access": "入力監視のアクセス権",
        "The input signal preference is saved. macOS permission is requested only when enabled.": "入力信号の設定は保存されます。macOS の権限は有効にした場合にのみ要求されます。",
        "Template profiles are built-in starting points and cannot be deleted.": "テンプレートプロファイルはあらかじめ用意されており、削除できません。",
        "Registered profiles are linked to an app and can be deleted.": "登録済みプロファイルはアプリに紐付いており、削除できます。",
        "Preview Profile": "プロファイルをプレビュー",
        "Active Profile": "アクティブなプロファイル",
        "Overlay tested": "オーバーレイのテスト完了",
        "Ready to test": "テストの準備完了",
        "Create a registered profile for the app you want to use.": "使用するアプリの登録済みプロファイルを作成してください。",
        "No app added": "アプリが追加されていません",
        "Adaptive Mode (Optional)": "適応モード（任意）",
        "Access requested": "アクセスを要求しました",
        "Optional step": "任意の手順",
        "Skip for Now": "今はスキップ",
        "Game Window": "ゲームウインドウ",
        "Game Window (Waiting for Game)": "ゲームウインドウ（ゲーム待機中）",
        "Active Game Display (Window Fallback)": "ゲーム画面（ウインドウ検出の代替）",
        "Compatibility": "互換性",
        "Startup": "起動",
        "Resolved Overlay Target": "現在のオーバーレイ対象",
        "The game window was not available, so SeaLegs is using the active game display.": "ゲームウインドウを取得できないため、現在のゲーム画面を使用しています。",
        "Launch SeaLegs at Login": "ログイン時に SeaLegs を起動",
        "Launch at Login Status": "ログイン時起動の状態",
        "Not Registered": "未登録",
        "Requires Approval": "承認が必要",
        "Unavailable": "利用不可",
        "Approve SeaLegs in System Settings > General > Login Items.": "システム設定 > 一般 > ログイン項目で SeaLegs を承認してください。",
        "Open Login Items Settings": "ログイン項目設定を開く",
        "Center Dot Horizontal Position": "中央ドットの水平位置",
        "Center Dot Vertical Position": "中央ドットの垂直位置",
        "Crosshair Horizontal Position": "クロスヘアの水平位置",
        "Crosshair Vertical Position": "クロスヘアの垂直位置",
        "Reset Anchor Positions": "アンカー位置をリセット",
        "Compatibility Check": "互換性チェック",
        "Run this check with the game visible to confirm targeting and Adaptive readiness.": "ゲームを表示した状態で、対象指定と適応モードの準備状態を確認してください。",
        "Registered Game": "登録済みゲーム",
        "Not Active": "未実行",
        "Active": "実行中",
        "Overlay Target": "オーバーレイ対象",
        "Adaptive Samples": "適応サンプル",
        "Launch at Login": "ログイン時に起動",
        "Run Overlay Test": "オーバーレイテストを実行",
        "Copy Compatibility Report": "互換性レポートをコピー",
        "The compatibility report contains operational status only and excludes screenshots, frames, paths, window titles, and raw application identifiers.": "互換性レポートには動作状態のみが含まれ、スクリーンショット、フレーム、パス、ウインドウタイトル、生のアプリ識別子は含まれません。",
        "Compatibility check not run yet.": "互換性チェックはまだ実行されていません。",
        "Overlay test started. Confirm that the visual guides fit the game area.": "オーバーレイテストを開始しました。視覚ガイドがゲーム領域に合っているか確認してください。",
        "Compatibility report copied.": "互換性レポートをコピーしました。",
        "Export Selected Profile...": "選択したプロファイルを書き出す...",
        "Import Profiles...": "プロファイルを読み込む...",
        "Export Custom Profiles...": "カスタムプロファイルを書き出す...",
        "Profile Import Preview": "プロファイル読み込みプレビュー",
        "%d profile(s) ready to import.": "%d 件のプロファイルを読み込めます。",
        "Conflicts": "競合",
        "Warnings": "警告",
        "Replace Existing": "既存を置き換える",
        "Import Profiles": "プロファイルを読み込む",
        "Keep Both": "両方を保持",
        "Export SeaLegs Profiles": "SeaLegs プロファイルを書き出す",
        "Import SeaLegs Profiles": "SeaLegs プロファイルを読み込む",
        "Select a profile before exporting.": "書き出すプロファイルを選択してください。",
        "No custom profiles are available to export.": "書き出せるカスタムプロファイルがありません。",
        "Review the imported profiles before applying changes.": "変更を適用する前に読み込むプロファイルを確認してください。",
        "Profile import failed: %@": "プロファイルの読み込みに失敗しました: %@",
        "Profile import cancelled.": "プロファイルの読み込みをキャンセルしました。",
        "Imported %d profile(s).": "%d 件のプロファイルを読み込みました。",
        "Launch at Login requires approval in System Settings.": "ログイン時起動にはシステム設定での承認が必要です。",
        "Launch at Login updated.": "ログイン時起動を更新しました。",
        "Failed to update Launch at Login: %@": "ログイン時起動の更新に失敗しました: %@",
        "Exported %d profile(s) to %@.": "%d 件のプロファイルを %@ に書き出しました。",
        "Profile export failed: %@": "プロファイルの書き出しに失敗しました: %@",
        "This profile has no app match and must be reconnected before automatic matching can work.": "このプロファイルには対応するアプリがありません。自動照合を使うにはゲームへ再接続してください。",
        "Built-in templates are protected and will be kept as separate profiles.": "組み込みテンプレートは保護され、別のプロファイルとして保持されます。",
        "Keep Both imports conflicting profiles without an app match to avoid ambiguous automatic activation.": "自動起動の競合を避けるため、「両方を保持」で読み込む競合プロファイルはアプリとの関連付けを解除します。",
        "A linked imported profile can activate automatically when its matching app becomes active.": "関連付けられた読み込みプロファイルは、一致するアプリがアクティブになると自動的に有効になる場合があります。",
        "Unlinked": "未関連付け",
        "Custom profile": "カスタムプロファイル",
        "Unlinked custom profiles can be previewed or linked to the current app.": "未関連付けのカスタムプロファイルは、プレビューするか現在のアプリに関連付けることができます。",
        "Link to Current App": "現在のアプリに関連付ける",
        "Select a custom profile before linking an app.": "アプリを関連付けるカスタムプロファイルを選択してください。",
        "No application is available to link.": "関連付け可能なアプリがありません。",
        "This app is already linked to %@.": "このアプリはすでに %@ に関連付けられています。",
        "Linked %@ to the selected profile.": "%@ を選択したプロファイルに関連付けました。",
        "App": "アプリ"
    ]

    private static let chineseSimplified: [String: String] = [
        "System Default": "系统默认",
        "Language": "语言",
        "Interface Language": "界面语言",
        "Language preference saved.": "语言设置已保存。",
        "Failed to save language preference: %@": "语言设置保存失败：%@",
        "General": "通用",
        "Profiles": "配置",
        "Overlay": "覆盖层",
        "Adaptive": "自适应",
        "Assistant": "助手",
        "Calibration": "校准",
        "Hotkeys": "快捷键",
        "Privacy": "隐私",
        "Reports": "报告",
        "Debug": "调试",
        "Status": "状态",
        "Current App": "当前应用",
        "Current Game": "当前游戏",
        "Mode": "模式",
        "Capture": "采集",
        "Message": "消息",
        "Actions": "操作",
        "Add Current App": "添加当前应用",
        "Toggle Overlay": "切换覆盖层",
        "Open Session Report": "打开会话报告",
        "Toggle Emergency": "切换紧急模式",
        "Support": "支持范围",
        "Supported: macOS 14+ on Apple Silicon, windowed/borderless games recommended.": "支持：Apple Silicon 上的 macOS 14+，建议使用窗口或无边框窗口游戏。",
        "Limited: native fullscreen games depending on macOS Spaces behavior.": "有限支持：原生全屏游戏可能受 macOS Spaces 行为影响。",
        "Comfort": "舒适度",
        "Off": "关闭",
        "Low": "低",
        "Medium": "中",
        "High": "高",
        "Vignette": "暗角",
        "Base Opacity": "基础不透明度",
        "Max Opacity": "最大不透明度",
        "Motion Inner Radius": "运动内半径",
        "Visual Anchors": "视觉锚点",
        "Center Dot": "中心点",
        "Center Dot Opacity": "中心点不透明度",
        "Minimal Crosshair": "简洁准星",
        "Crosshair Opacity": "准星不透明度",
        "Horizon Guide": "地平线引导",
        "Horizon Position": "地平线位置",
        "Dashboard Frame": "仪表盘框架",
        "Virtual Nose": "虚拟鼻尖",
        "Peripheral Frame": "周边框架",
        "Peripheral Frame Opacity": "周边框架不透明度",
        "Current Overlay": "当前覆盖层",
        "Opacity": "不透明度",
        "Inner Radius": "内半径",
        "Emergency": "紧急",
        "On": "开启",
        "Screen Recording": "屏幕录制",
        "Access": "权限",
        "Granted": "已允许",
        "Not Granted": "未允许",
        "Request Access": "请求权限",
        "Open Privacy Settings": "打开隐私设置",
        "Refresh": "刷新",
        "Restart SeaLegs": "重启 SeaLegs",
        "After allowing SeaLegs in System Settings, return here and press Refresh.": "在系统设置中允许 SeaLegs 后，回到这里并点击刷新。",
        "After allowing SeaLegs in System Settings, restart SeaLegs, then press Refresh.": "在系统设置中允许 SeaLegs 后，重启 SeaLegs，然后点击刷新。",
        "Metrics": "指标",
        "Motion Score": "运动评分",
        "Peripheral Motion": "周边运动",
        "Rotation Proxy": "旋转估计",
        "Radial Expansion": "径向扩张",
        "Visual Cadence Risk": "视觉节奏风险",
        "Game Settings Assistant": "游戏设置助手",
        "These recommendations are manual. SeaLegs will not change game files automatically.": "这些建议需要手动应用。SeaLegs 不会自动修改游戏文件。",
        "Profile": "配置",
        "Checklist": "检查清单",
        "No profile is available.": "没有可用配置。",
        "Reset Checklist for Profile Category": "重置此配置类别的清单",
        "Reset this checklist?": "要重置此清单吗？",
        "Reset Checklist": "重置清单",
        "Cancel": "取消",
        "Critical": "关键",
        "Recommended": "推荐",
        "Optional": "可选",
        "Not Checked": "未检查",
        "Applied": "已应用",
        "Ignored": "已忽略",
        "Not Available": "游戏中不可用",
        "Almost never uncomfortable": "几乎不会不适",
        "Sometimes uncomfortable": "有时不适",
        "Often uncomfortable": "经常不适",
        "Very sensitive": "非常敏感",
        "Subtle center dot": "轻微中心点",
        "No anchor": "无锚点",
        "Calibration Wizard": "校准向导",
        "Calibration works without Screen Recording permission and updates the selected profile after confirmation.": "校准无需屏幕录制权限，确认后会更新所选配置。",
        "Target Profile": "目标配置",
        "Game Type": "游戏类型",
        "Category": "类别",
        "Sensitivity": "敏感度",
        "Visual Anchor": "视觉锚点",
        "Preference": "偏好",
        "Review / Apply Calibration": "检查 / 应用校准",
        "Undo Last Calibration": "撤销上次校准",
        "Apply calibration to selected profile?": "要将校准应用到所选配置吗？",
        "Apply Calibration": "应用校准",
        "This will update overlay strength, category, and checklist for the selected profile.": "这会更新所选配置的覆盖层强度、类别和检查清单。",
        "Defaults": "默认",
        "Fallback": "备用",
        "All core actions are also available from the SeaLegs menu bar item.": "所有核心操作也可从 SeaLegs 菜单栏项目使用。",
        "Registered": "已注册",
        "Unavailable (%d)": "不可用 (%d)",
        "Local Analysis": "本地分析",
        "Adaptive mode uses Screen Recording to process low-resolution frames locally.": "自适应模式使用屏幕录制在本地处理低分辨率帧。",
        "No screenshots, video, audio, OCR, typed text, or raw mouse paths are stored.": "不会存储截图、视频、音频、OCR、输入文字或原始鼠标路径。",
        "Only numeric motion metrics and optional discomfort ratings are written to session logs.": "会话日志只写入数值运动指标和可选的不适评分。",
        "Permissions": "权限",
        "Screen Recording Requested": "已请求屏幕录制",
        "Input Monitoring": "输入监控",
        "Yes": "是",
        "No": "否",
        "Enabled": "已启用",
        "Optional, off by default": "可选，默认关闭",
        "Request Screen Recording": "请求屏幕录制",
        "Open Screen Recording Settings": "打开屏幕录制设置",
        "Enable Input Signal": "启用输入信号",
        "Open Input Monitoring Settings": "打开输入监控设置",
        "Session Logs": "会话日志",
        "Store numeric session logs": "存储数值会话日志",
        "Sample interval: %.1fs": "采样间隔：%.1f 秒",
        "Retention: %d days": "保留：%d 天",
        "Delete Stored Session Logs...": "删除已存会话日志...",
        "Delete all stored session logs?": "要删除所有已存会话日志吗？",
        "Delete Logs": "删除日志",
        "Diagnostics": "诊断",
        "Diagnostics export includes numeric state and salted hashes, not screenshots, videos, OCR, typed text, raw app identifiers, or full paths.": "诊断导出包含数值状态和加盐哈希，不包含截图、视频、OCR、输入文字、原始应用标识符或完整路径。",
        "Export Diagnostics...": "导出诊断...",
        "Refresh Report": "刷新报告",
        "Template profile": "模板配置",
        "Display Name": "显示名称",
        "Match": "匹配",
        "Bundle ID": "Bundle ID",
        "Executable": "可执行文件",
        "Preview / Use": "预览 / 使用",
        "Delete": "删除",
        "Select a profile.": "请选择一个配置。",
        "Delete this profile?": "要删除此配置吗？",
        "Delete Profile": "删除配置",
        "Comfort overlay for macOS 3D games.": "适用于 macOS 3D 游戏的舒适覆盖层。",
        "Add Current App as Game": "将当前应用添加为游戏",
        "Test Overlay": "测试覆盖层",
        "Enable Adaptive Mode": "启用自适应模式",
        "Open Settings": "打开设置",
        "Screen Recording is only needed for Adaptive mode. Basic overlay works without permissions.": "只有自适应模式需要屏幕录制。基础覆盖层无需权限即可工作。",
        "Done": "完成",
        "Duration": "时长",
        "Average Motion": "平均运动",
        "Peak Motion": "峰值运动",
        "Average Discomfort": "平均不适",
        "Emergency Count": "紧急次数",
        "Recommendations": "建议",
        "High Risk Moments": "高风险时刻",
        "No session report yet.": "暂无会话报告。",
        "Game": "游戏",
        "Readiness": "就绪状态",
        "Last Sample": "最近样本",
        "No samples yet": "暂无样本",
        "%.1fs ago": "%.1f 秒前",
        "Current App: %@": "当前应用：%@",
        "Current Game: %@": "当前游戏：%@",
        "Emergency Mode": "紧急模式",
        "Add Current App as Game...": "将当前应用添加为游戏...",
        "Record Discomfort Score...": "记录不适评分...",
        "Open Settings...": "打开设置...",
        "Session Report...": "会话报告...",
        "Debug HUD": "调试 HUD",
        "Welcome to SeaLegs": "欢迎使用 SeaLegs",
        "Session Report": "会话报告",
        "Export SeaLegs Diagnostics": "导出 SeaLegs 诊断",
        "Quit": "退出",
        "Overlay Toggle": "切换覆盖层",
        "Comfort Up": "提高舒适度",
        "Comfort Down": "降低舒适度",
        "Discomfort Score": "不适评分",
        "%@ overlay preview is visible.": "%@ 覆盖层预览已显示。",
        "Preview": "预览",
        "Emergency comfort": "紧急舒适模式",
        "Stability %.0f%% · %@": "稳定性 %.0f%% · %@",
        "Record discomfort score": "记录不适评分",
        "0 = none, 20 = clear motion sickness.": "0 = 无，20 = 明显晕动。",
        "Record": "记录",
        "Desktop FPS": "桌面 FPS",
        "Competitive FPS": "竞技 FPS",
        "Third-person Action": "第三人称动作",
        "Racing": "竞速",
        "Flight / Space": "飞行 / 太空",
        "Walking Simulator": "步行模拟",
        "General 3D": "通用 3D",
        "Motion Blur": "动态模糊",
        "Camera Shake": "镜头晃动",
        "Head Bob / View Bob": "头部晃动 / 视角晃动",
        "Weapon Sway": "武器摆动",
        "Chromatic Aberration": "色差",
        "Film Grain": "胶片颗粒",
        "Depth of Field": "景深",
        "Sprint FOV Effect": "冲刺 FOV 效果",
        "Mouse Acceleration": "鼠标加速",
        "Auto Camera Recenter": "自动镜头回正",
        "Field of View": "视野",
        "Cockpit or Dashboard View": "驾驶舱或仪表盘视角",
        "Horizon / Cockpit Reference": "地平线 / 驾驶舱参照",
        "Off or Low": "关闭或低",
        "Low or Off": "低或关闭",
        "Tune after calibration": "校准后调整",
        "Prefer stable cockpit/dashboard view when available": "可用时优先使用稳定的驾驶舱/仪表盘视角",
        "Reduces visual smear during camera movement and sprinting.": "减少镜头移动和冲刺时的视觉拖影。",
        "Keeps the whole image from shaking during impacts, sprinting, and scripted events.": "减少撞击、冲刺和剧情事件中的整体画面晃动。",
        "Reduces repeated vertical camera motion while walking or running.": "减少行走或奔跑时反复的垂直镜头运动。",
        "Keeps the center view steadier during movement.": "让移动中的中心视野更稳定。",
        "Removes color fringing near the edge of the image.": "去除画面边缘附近的色彩边缘。",
        "Removes unnecessary visual noise.": "去除不必要的视觉噪点。",
        "Reduces sudden focus shifts and blur changes.": "减少突然的焦点变化和模糊变化。",
        "Avoids abrupt field-of-view changes while sprinting.": "避免冲刺时视野突然变化。",
        "Makes camera movement more predictable.": "让镜头运动更可预测。",
        "Reduces camera motion that was not directly initiated by the player.": "减少并非玩家直接发起的镜头运动。",
        "Very low and very high FOV values can both feel uncomfortable depending on the game.": "视游戏而定，过低或过高的 FOV 都可能造成不适。",
        "A fixed vehicle reference can make rapid lateral motion easier to tolerate.": "固定的载具参照可让快速横向运动更容易忍受。",
        "A fixed horizon or cockpit frame gives your eyes a stable reference.": "固定的地平线或驾驶舱框架可为眼睛提供稳定参照。",
        "Motion": "运动",
        "Motion score stayed high": "运动评分持续偏高",
        "User discomfort score reached %@": "用户不适评分达到 %@",
        "In-game settings checklist": "游戏内设置检查清单",
        "Turn down or disable Motion Blur, Camera Shake, Head Bob, Chromatic Aberration, Film Grain, and Sprint FOV Effect.": "建议调低或关闭动态模糊、镜头晃动、头部晃动、色差、胶片颗粒和冲刺 FOV 效果。",
        "Reduce camera rotation": "降低镜头旋转",
        "Camera rotation was strong. Try lowering in-game mouse sensitivity or turn speed.": "镜头旋转较强。可以尝试降低游戏内鼠标灵敏度或转向速度。",
        "Reduce sprint and FOV effects": "降低冲刺和 FOV 效果",
        "Fast forward-motion sections were frequent. Try lowering sprint FOV effect, motion blur, and camera shake.": "快速前进片段较多。可以尝试降低冲刺 FOV 效果、动态模糊和镜头晃动。",
        "Reduce vertical bobbing": "降低垂直晃动",
        "Vertical motion was strong. Turning off head bob or view bob is recommended.": "垂直运动较强。建议关闭头部晃动或视角晃动。",
        "Improve frame stability": "改善帧稳定性",
        "Visual stability was low. Try lowering graphics settings or setting a stable FPS cap.": "视觉稳定性较低。可以尝试降低图形设置或设置稳定的 FPS 上限。",
        "Increase profile strength": "提高配置强度",
        "Emergency mode or high discomfort was recorded. Consider raising the current profile's vignette max strength by one step.": "记录到紧急模式或较高不适感。可考虑将当前配置的暗角最大强度提高一级。",
        "Keep current settings": "保持当前设置",
        "High-risk signals were limited. Keeping the current comfort profile is reasonable.": "高风险信号较少。保持当前舒适配置是合理的。",
        "Ready": "就绪",
        "Basic overlay available": "基础覆盖层可用",
        "No diagnostics export yet.": "尚未导出诊断。",
        "None": "无",
        "stopped": "已停止",
        "preview": "预览",
        "fallback: basic overlay": "备用：基础覆盖层",
        "Screen Recording required": "需要屏幕录制",
        "Waiting for samples": "等待样本",
        "Some hotkeys could not be registered. Use the menu bar actions as fallback.": "部分快捷键无法注册。请使用菜单栏操作作为备用。",
        "Screen Recording permission granted.": "屏幕录制权限已授予。",
        "Allow Screen Recording in System Settings, then return to SeaLegs and press Refresh.": "请在系统设置中允许屏幕录制，然后返回 SeaLegs 并点击刷新。",
        "Allow Screen Recording in System Settings, restart SeaLegs, then press Refresh.": "请在系统设置中允许屏幕录制，重启 SeaLegs，然后点击刷新。",
        "Open Privacy & Security > Screen Recording manually, allow SeaLegs, restart the app, then press Refresh.": "请手动打开隐私与安全性 > 屏幕录制，允许 SeaLegs，重启应用，然后点击刷新。",
        "If SeaLegs is enabled in Screen Recording, restart the app and press Refresh.": "如果 SeaLegs 已在屏幕录制中启用，请重启应用并点击刷新。",
        "Use Request Access to open Screen Recording settings, allow SeaLegs, restart the app, then press Refresh.": "请点击请求权限打开屏幕录制设置，允许 SeaLegs，重启应用，然后点击刷新。",
        "Failed to restart SeaLegs: %@": "重启 SeaLegs 失败：%@",
        "Input signal monitoring enabled.": "输入信号监控已启用。",
        "Input Monitoring permission is needed for mouse turn prediction.": "鼠标转向预测需要输入监控权限。",
        "Allow Input Monitoring in System Settings, restart SeaLegs, then press Refresh.": "请在系统设置中允许输入监控，重启 SeaLegs，然后点击刷新。",
        "Open Privacy & Security > Input Monitoring manually, allow SeaLegs, restart the app, then press Refresh.": "请手动打开隐私与安全性 > 输入监控，允许 SeaLegs，重启应用，然后点击刷新。",
        "Diagnostics exported.": "诊断已导出。",
        "Exported to %@.": "已导出到 %@。",
        "Export failed: %@": "导出失败：%@",
        "Privacy settings saved.": "隐私设置已保存。",
        "Stored session logs deleted.": "已删除存储的会话日志。",
        "Adaptive capture fallback: %@": "自适应采集备用：%@",
        "Adaptive paused": "自适应已暂停",
        "Select a registered game to enable adaptive capture.": "请选择已注册游戏以启用自适应采集。",
        "Adaptive requires an active registered game.": "自适应需要一个正在运行的已注册游戏。",
        "Screen Recording permission needed": "需要屏幕录制权限",
        "Adaptive waiting": "自适应等待中",
        "Temporary stronger overlay": "临时增强覆盖层",
        "Interface": "界面",
        "Overlay Display": "覆盖层显示范围",
        "Active Game Display": "当前游戏所在显示器",
        "All Displays": "所有显示器",
        "Overlay display preference saved.": "覆盖层显示范围设置已保存。",
        "Open SeaLegs controls": "打开 SeaLegs 控制菜单",
        "%@ overlay is off.": "%@ 覆盖层已关闭。",
        "%@ is already registered.": "%@ 已注册。",
        "manual overlay": "手动覆盖层",
        "Overlay hidden.": "覆盖层已隐藏。",
        "Overlay visible.": "覆盖层已显示。",
        "Input signal preference saved.": "输入信号设置已保存。",
        "Input signal monitoring disabled.": "输入信号监控已禁用。",
        "Input Monitoring permission is needed. The input signal will start automatically after permission is granted and SeaLegs is reopened.": "需要输入监控权限。授予权限并重新打开 SeaLegs 后，输入信号将自动启动。",
        "paused while Mac sleeps": "Mac 睡眠时已暂停",
        "Hotkeys registered.": "快捷键已注册。",
        "Some hotkeys are unavailable. Use the menu bar actions as fallback.": "部分快捷键不可用。请使用菜单栏操作作为替代。",
        "Emergency overlay ended. Record discomfort when it is safe to do so.": "紧急覆盖层已结束。请在安全时记录不适评分。",
        "Built-in template profiles cannot be deleted.": "内置模板配置无法删除。",
        "Start a registered game before recording a discomfort score.": "请先启动已注册的游戏，再记录不适评分。",
        "Failed to save settings: %@": "设置保存失败：%@",
        "Add a game profile before applying calibration.": "请先添加游戏配置，再应用校准。",
        "Session logs may contain numeric motion metrics, profile identifiers, permission state, optional discomfort ratings, and emergency events.": "会话日志可能包含数值运动指标、配置标识符、权限状态、可选的不适评分和紧急事件。",
        "Template profile names and categories are fixed, but their visual settings can be adjusted.": "模板配置的名称和类别不可更改，但其视觉设置可以调整。",
        "Bring the game to the front once, return to SeaLegs, then add it.": "先将游戏切换到前台一次，再返回 SeaLegs 添加它。",
        "System": "系统",
        "Show Feature Demo": "显示功能演示",
        "Feature demo overlay is visible.": "功能演示覆盖层已显示。",
        "Shows center dot, crosshair, horizon, dashboard, nose, and peripheral frame.": "显示中心点、准星、地平线引导、仪表盘框架、虚拟鼻尖和周边框架。",
        "Feature demo temporarily shows every visible aid at high contrast, without changing the selected profile.": "功能演示会以高对比度暂时显示所有可见辅助元素，且不会更改所选配置。",
        "Apply Recommended Visual Aids": "应用推荐的视觉辅助",
        "Recommended visual aids applied.": "已应用推荐的视觉辅助。",
        "Last calibration undone.": "已撤销上次校准。",
        "Failed to save profiles: %@": "保存配置失败：%@",
        "feature demo": "功能演示",
        "Adaptive Analysis": "自适应分析",
        "Low Power Mode": "低功耗模式",
        "Analysis FPS: %d": "分析 FPS：%d",
        "Effective FPS": "实际 FPS",
        "Low Power Mode caps analysis at 12 FPS and reduces analysis resolution.": "低功耗模式会将分析帧率限制为 12 FPS，并降低分析分辨率。",
        "Discomfort Prompts": "不适提示",
        "Periodic discomfort prompts": "定期不适提示",
        "Prompt interval: %d min": "提示间隔：%d 分钟",
        "Editing Profile": "正在编辑的配置",
        "Profile Type": "配置类型",
        "Registered profile": "已注册配置",
        "Registration": "注册状态",
        "Retry Hotkey Registration": "重新注册快捷键",
        "Input Signal": "输入信号",
        "Input Monitoring Access": "输入监控权限",
        "The input signal preference is saved. macOS permission is requested only when enabled.": "输入信号设置已保存。仅在启用时请求 macOS 权限。",
        "Template profiles are built-in starting points and cannot be deleted.": "模板配置是内置的起始配置，无法删除。",
        "Registered profiles are linked to an app and can be deleted.": "已注册配置与应用关联，并且可以删除。",
        "Preview Profile": "预览配置",
        "Active Profile": "当前生效配置",
        "Overlay tested": "覆盖层测试完成",
        "Ready to test": "已准备好测试",
        "Create a registered profile for the app you want to use.": "请为要使用的应用创建已注册配置。",
        "No app added": "尚未添加应用",
        "Adaptive Mode (Optional)": "自适应模式（可选）",
        "Access requested": "已请求权限",
        "Optional step": "可选步骤",
        "Skip for Now": "暂时跳过",
        "Game Window": "游戏窗口",
        "Game Window (Waiting for Game)": "游戏窗口（等待游戏）",
        "Active Game Display (Window Fallback)": "当前游戏显示器（窗口检测备用）",
        "Compatibility": "兼容性",
        "Startup": "启动",
        "Resolved Overlay Target": "当前覆盖层目标",
        "The game window was not available, so SeaLegs is using the active game display.": "无法获取游戏窗口，因此 SeaLegs 正在使用当前游戏显示器。",
        "Launch SeaLegs at Login": "登录时启动 SeaLegs",
        "Launch at Login Status": "登录时启动状态",
        "Not Registered": "未注册",
        "Requires Approval": "需要批准",
        "Unavailable": "不可用",
        "Approve SeaLegs in System Settings > General > Login Items.": "请在系统设置 > 通用 > 登录项中批准 SeaLegs。",
        "Open Login Items Settings": "打开登录项设置",
        "Center Dot Horizontal Position": "中心点水平位置",
        "Center Dot Vertical Position": "中心点垂直位置",
        "Crosshair Horizontal Position": "准星水平位置",
        "Crosshair Vertical Position": "准星垂直位置",
        "Reset Anchor Positions": "重置锚点位置",
        "Compatibility Check": "兼容性检查",
        "Run this check with the game visible to confirm targeting and Adaptive readiness.": "请在游戏可见时运行检查，以确认目标和自适应准备状态。",
        "Registered Game": "已注册游戏",
        "Not Active": "未运行",
        "Active": "运行中",
        "Overlay Target": "覆盖层目标",
        "Adaptive Samples": "自适应样本",
        "Launch at Login": "登录时启动",
        "Run Overlay Test": "运行覆盖层测试",
        "Copy Compatibility Report": "复制兼容性报告",
        "The compatibility report contains operational status only and excludes screenshots, frames, paths, window titles, and raw application identifiers.": "兼容性报告仅包含运行状态，不包含截图、帧、路径、窗口标题或原始应用标识符。",
        "Compatibility check not run yet.": "尚未运行兼容性检查。",
        "Overlay test started. Confirm that the visual guides fit the game area.": "覆盖层测试已开始。请确认视觉引导与游戏区域相符。",
        "Compatibility report copied.": "兼容性报告已复制。",
        "Export Selected Profile...": "导出所选配置...",
        "Import Profiles...": "导入配置...",
        "Export Custom Profiles...": "导出自定义配置...",
        "Profile Import Preview": "配置导入预览",
        "%d profile(s) ready to import.": "已准备导入 %d 个配置。",
        "Conflicts": "冲突",
        "Warnings": "警告",
        "Replace Existing": "替换现有配置",
        "Import Profiles": "导入配置",
        "Keep Both": "两者都保留",
        "Export SeaLegs Profiles": "导出 SeaLegs 配置",
        "Import SeaLegs Profiles": "导入 SeaLegs 配置",
        "Select a profile before exporting.": "请先选择要导出的配置。",
        "No custom profiles are available to export.": "没有可导出的自定义配置。",
        "Review the imported profiles before applying changes.": "应用更改前请检查要导入的配置。",
        "Profile import failed: %@": "配置导入失败：%@",
        "Profile import cancelled.": "已取消配置导入。",
        "Imported %d profile(s).": "已导入 %d 个配置。",
        "Launch at Login requires approval in System Settings.": "登录时启动需要在系统设置中批准。",
        "Launch at Login updated.": "登录时启动设置已更新。",
        "Failed to update Launch at Login: %@": "更新登录时启动失败：%@",
        "Exported %d profile(s) to %@.": "已将 %d 个配置导出到 %@。",
        "Profile export failed: %@": "配置导出失败：%@",
        "This profile has no app match and must be reconnected before automatic matching can work.": "此配置没有匹配的应用。要使用自动匹配，请重新关联游戏。",
        "Built-in templates are protected and will be kept as separate profiles.": "内置模板受保护，并将作为单独配置保留。",
        "Keep Both imports conflicting profiles without an app match to avoid ambiguous automatic activation.": "为避免自动激活冲突，使用“两者都保留”导入的冲突配置将取消应用关联。",
        "A linked imported profile can activate automatically when its matching app becomes active.": "已关联的导入配置可能会在匹配的应用变为活动状态时自动启用。",
        "Unlinked": "未关联",
        "Custom profile": "自定义配置",
        "Unlinked custom profiles can be previewed or linked to the current app.": "未关联的自定义配置可以预览，也可以关联到当前应用。",
        "Link to Current App": "关联到当前应用",
        "Select a custom profile before linking an app.": "请先选择要关联应用的自定义配置。",
        "No application is available to link.": "没有可关联的应用。",
        "This app is already linked to %@.": "此应用已关联到 %@。",
        "Linked %@ to the selected profile.": "已将 %@ 关联到所选配置。",
        "App": "应用"
    ]

}
